filebeat.inputs:
  - type: filestream
    id: nginx-logs
    enabled: true
    paths:
      - /var/log/nginx/*.log
    fields:
      service: nginx
      type: access
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_locale: {}

  - type: filestream
    id: laravel-logs
    enabled: true
    paths:
      - /var/www/html/storage/logs/*.log
    fields:
      service: laravel
      type: app
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elastic:9200"]
setup.kibana:
  host: "kibana:5601"
